stages:
    - test
    - pages
    - coverage

test:
    stage: test
    script:
        - make test -B
        - make clean

coverage:
    stage: coverage
    script:
        - make coverage
        - make clean
pages:
    stage: pages
    allow_failure: true
    artifacts:
        paths:
            - site
    script:
        - cd docs && mkdocs build
