stages:
    - test
    - coverage
    - doc

test:
    stage: test
    script:
        - make test -B
        - make clean

coverage:
    stage: coverage
    script:
        - make coverage
        - make clean


doc:
    stage: doc
    script:
        - make doc -B
        - git clone https://tpoisot:$GITBOOK_TOKEN@git.gitbook.com/poisotlab/befwm.git gitdoc
        - cp doc/* gitdoc/
        - cd gitdoc
        - git remote set-url gitbook https://tpoisot:$GITBOOK_TOKEN@git.gitbook.com/poisotlab/befwm.git
        - git add .
        - git commit -m 'Doc update'
        - git push -u gitbook master -f
