stages:
    - pages
    - coverage

coverage:
    stage: coverage
    script:
        - make coverage
        - make clean
pages:
    stage: pages
    allow_failure: true
    artifacts:
        paths:
            - docs/site
    script:
        - cd docs && mkdocs build
