test:
    script:
        - make test -B
        - make clean

mirror:
    script:
        - git clone --mirror git@github.com:PoisotLab/befwm.git
        - cd mirror
        - git remote set-url --push origin git@github.com:PoisotLab/befwm.git
        - git fetch -p origin
        - git push --mirror
