test:
    script:
        - make test -B
        - make clean

mirror:
    script:
        - git clone --mirror https://github.com/PoisotLab/befwm.git mirror
        - cd mirror
        - git remote set-url --push origin https://github.com/PoisotLab/befwm
        - git fetch -p origin
        - git push --mirror
