language: julia
sudo: false
os:
    - linux
    - osx
julia:
    - release
    - nightly
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("befwm"); Pkg.test("befwm"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("befwm")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
