site_name: BioEnergeticFoodWebs.jl
repo_url: https://github.com/PoisotLab/BioEnergeticFoodWebs.jl
site_description: Simulation of biomass dynamics on food webs
site_author: the Poisot lab

theme: material

extra:
    logo: 'befw.png'
    palette:
        primary: purple
        accent: teal
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    author:
        twitter: 'poisotlab'

extra_css:
    - asssets/Documenter.css

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - assets/mathjaxhelper.js

markdown_extensions:
    - fenced_code
    - extra
    - tables
    - mdx_math

docs_dir: 'build'

pages:
    - Home: index.md
    - Manual:
        - Installation: man/installation.md
    - Library:
        - Public: lib/public.md
        - Internals: lib/internals.md
