site_name: befwm.jl
repo_url:  http://poisotlab.biol.umontreal.ca/julia-pakages/befwm
site_author: The Poisot Lab

docs_dir: 'build'
theme: readthedocs
pages:
    - Home: index.md
    - User guide:
        - Introduction: user/userguide.md
        - Generating networks: user/user_random.md
        - Simulations: user/user_general.md
        - Measures on outpût: user/user_measures.md
    - Reference: api.md
    - License: LICENSE.md
    - Release notes: CHANGELOG.md
