site_name: Documentation for befwm.jl
repo_url:  http://poisotlab.biol.umontreal.ca/julia-packages/befwm
repo_name: GitLab repo
site_author: The Poisot Lab

docs_dir: 'build'
theme: flatly
pages:
    - Home: index.md
    - User guide:
        - Introduction: user/userguide.md
        - Generating networks: user/user_random.md
        - Simulations: user/user_general.md
        - Measures on output: user/user_measures.md
    - Reference: api.md
    - License: LICENSE.md
    - Release notes: CHANGELOG.md
